### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by ramyarad** [jensgerdes/sonar-pmd#77]
HI,

I got this error (pasted the error below) while running sonar analysis for a project that is compiled using JDK 1.6 , we have upgraded our sonarqube to 6.7.5 and the sonar-pmd plugin is also upgraded to 3.1.1.

[sonar:sonar] Sensor PmdSensor [pmd]
[sonar:sonar] Execute PMD 6.9.0
[sonar:sonar] Java version: 1.6
[sonar:sonar] PMD configuration: /home/jenkins/workspace/Software Deployment/SonarBuildOnline/specialUse/EPS_Build/.sonar/pmd.xml
[sonar:sonar] Execute PMD 6.9.0 (done) | time=64428ms

BUILD FAILED
/home/jenkins/workspace/Software Deployment//build.xml:158: The following error occurred while executing this line:
/home/jenkins/workspace/Software Deployment/SonarBuildOnline//sonar_build.xml:174: java.lang.IncompatibleClassChangeError: com.uhg.exante.online.form.InvoiceForm and com.uhg.exante.online.form.InvoiceForm$MonthYearTO disagree on InnerClasses attribute
               at java.lang.Class.getDeclaringClass0(Native Method)
               at java.lang.Class.getDeclaringClass(Class.java:1235)
               at java.lang.Class.getEnclosingClass(Class.java:1277)
               at java.lang.Class.getSimpleBinaryName(Class.java:1443)
               at java.lang.Class.getSimpleName(Class.java:1309)
               at java.lang.Class.isAnonymousClass(Class.java:1411)
               at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.<init>(JavaTypeDefinitionSimple.java:46)
            at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinition.forClass(JavaTypeDefinition.java:74)

Any help is highly appreciated.

**Comment by jensgerdes** [comment]
Hi @ramyarad 

This looks like a PMD problem, not one of the SonarQube plugin.
Nonetheless, I'll look into this within the next few weeks.

**Comment by mauhiz** [comment]
Hi, having the same issue with `Java version: 1.8`; and it's been happening for several versions of PMD.

**Comment by jborgers** [comment]
Is this still relevant?
